Update Cargo.kamal
neodyme-labs/solana-security-txt pull request #53
Opened 2024-07-09 00:34 UTC by Kamal-arc

2024-07-12 09:51 UTC, nowakwp reviewed
H5pn5VpUvGbQ8WmA9GBQyfZ3bVVNvoJvpbrwT6dTXmYB

2024-07-12 09:51 UTC, nowakwp commented on query-security-txt/Cargo.toml
> -edition = "2021"
Hshha

2024-07-12 09:54 UTC, nowakwp reviewed
H5pn5VpUvGbQ8WmA9GBQyfZ3bVVNvoJvpbrwT6dTXmYB

2024-07-12 09:54 UTC, nowakwp commented on query-security-txt/Cargo.toml
>  [package]
H5pn5VpUvGbQ8WmA9GBQyfZ3bVVNvoJvpbrwT6dTXmYB

2024-07-12 09:56 UTC, nowakwp reviewed
H5pn5VpUvGbQ8WmA9GBQyfZ3bVVNvoJvpbrwT6dTXmYB

2024-07-12 09:58 UTC, nowakwp commented
> H5pn5VpUvGbQ8WmA9GBQyfZ3bVVNvoJvpbrwT6dTXmYB



> H5pn5VpUvGbQ8WmA9GBQyfZ3bVVNvoJvpbrwT6dTXmYB

2024-07-12 09:58 UTC, nowakwp reviewed
H5pn5VpUvGbQ8WmA9GBQyfZ3bVVNvoJvpbrwT6dTXmYB

2024-07-27 00:24 UTC, Sturgeontara06 requested changes
Don't have a clue

2024-09-06 03:23 UTC, Elgayar777 approved these changes

2024-09-06 03:23 UTC, Elgayar777 reviewed
.

2024-09-24 22:21 UTC, Sturgeontara06 approved these changes

2024-09-26 10:08 UTC, closed without merging

2024-12-14 12:02 UTC, Sturgeontara06 reviewed
Ok

2024-12-14 20:43 UTC, JanKortes212 commented
What the adres is this?